# Site settings
title: "Roozbeh Ehsani Resume"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Roozbeh Ehsani"
resume_title:                   "Graduate Research Scientist, Data Scientist"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "ehsan010@umn.edu"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "734-510-4673"
resume_contact_address:         "Minneapolis, MN(Open to Relocation)"

resume_header_contact_info:     "Minneapolis, MN(Open to Relocation) • 734-510-4673 • ehsan010@umn.edu"
display_header_contact_info:    "true"

resume_header_intro: "<p align = justify>I am a Ph.D. candidate specializing in turbulence modeling, where I developed high-fidelity generative stochastic models. I implemented a pipeline for exploratory data analysis of turbulent flow datasets and collected statistics of underlying structures. Using these insights, I built a fast, parallelizable stochastic model capable of reproducing key turbulence statistics and energy spectra with high accuracy. Alongside my Ph.D., I earned a second Master’s degree in Computer Science, where I studied, implemented, and evaluated multiple data science projects that strengthened my expertise in machine learning, statistical analysis, and database management systems.<br>
  <p align = justify> In Summer 2025, I joined Solventum (formerly 3M) as a Data Science Intern, contributing to a $3B strategic project. I built an interactive Dash/Cytoscape web app to visualize material connectivity, applied clustering models to optimize testing, and collaborated with cross-functional teams to translate business needs into scalable, data-driven solutions.</p>
  <p align = justify> I look forward to applying this blend of deep research experience and practical data science skills to solve real-world challenges in innovative teams.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false
resume_section_interests:       false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/Roozbeh96"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/roozbeh-ehsani/"
  resume_googlescholar_url:   "https://scholar.google.com/citations?user=9IW2X1QAAAAJ&hl=en"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
